name = "eternize-page"
main = "build/index.js"
compatibility_date = "2026-04-25"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[[d1_databases]]
binding = "ETERNIZE-DB"
database_name = "eternize-db"
database_id = "61807ca7-0820-4d0c-862f-0521aa47f150"
